from enum import Enum

from shared.const import ACTIONBONUSSTRING, ACTIONFREESTRING, ACTIONMAINSTRING, ACTIONMOVEMENTSTRING, EQUIPMENTACCESSORYSTRING, EQUIPMENTARMORSTRING, EQUIPMENTBOOTSSTRING, EQUIPMENTMAINHANDSTRING, EQUIPMENTOFFHANDSTRING, EQUIPMENTTWOHANDSTRING, PHASEACTIVEUNITSTRING, PHASEDEPLOYMENTSTRING, PHASEGAMEOVERSTRING, PHASESELECTINGUNITSTRING, STATACCURACYSTRING, STATARMORSTRING, STATEVASIONSTRING, STATMAXHEALTHSTRING, STATMOVEMENTSTRING

class ActionHandler(str, Enum):
    Effect = "effects"
    Ability = "ability"
    DeployUnit = "deploy"
    SelectUnit = "selectUnit"
    EndTurn = "endTurn"

class EquipmentSlot(str, Enum):
    ARMOR = EQUIPMENTARMORSTRING
    ACCESSORY = EQUIPMENTACCESSORYSTRING
    MAINHAND = EQUIPMENTMAINHANDSTRING
    OFFHAND = EQUIPMENTOFFHANDSTRING
    TWOHAND = EQUIPMENTTWOHANDSTRING
    BOOTS = EQUIPMENTBOOTSSTRING

class StatName(str, Enum):
    MAXHEALTH = STATMAXHEALTHSTRING
    ARMOR = STATARMORSTRING
    EVASION = STATEVASIONSTRING
    ACCURACY = STATACCURACYSTRING
    MOVEMENT = STATMOVEMENTSTRING

class ActionSlot(str, Enum):
    BONUS = ACTIONBONUSSTRING
    MAIN = ACTIONMAINSTRING
    MOVE = ACTIONMOVEMENTSTRING
    FREE = ACTIONFREESTRING

class GamePhase(str, Enum):
    DEPLOYMENT = PHASEDEPLOYMENTSTRING
    ACTIVE_UNIT = PHASEACTIVEUNITSTRING
    SELECTING_UNIT = PHASESELECTINGUNITSTRING
    GAME_OVER = PHASEGAMEOVERSTRING